trigger:
  branches:
    include:
      - main
      - dev
      - test

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals LAPTOP-DROUUN5U

variables:
  - group: vercel-deploy-group
  - name: node_version
    value: '18'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Frontend Only
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            workingDirectory: Frontend
            displayName: 'Build Frontend'

  - stage: Test
    dependsOn: Build
    displayName: Test Stage
    jobs:
      - job: TestJob
        displayName: Run Tests
        steps:
          - checkout: self

          - script: |
              npm ci
              npm test
            workingDirectory: Frontend
            displayName: 'Test Frontend'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'Backend Unit Tests'
              failTaskOnMissingResultsFile: false
            condition: succeededOrFailed()
            displayName: 'Publish Test Results'

  - stage: Deploy
    dependsOn: Test
    displayName: Deploy Stage
    jobs:
      - job: DeployJob
        displayName: Deploy Frontend and Backend
        steps:
          - checkout: self

          - script: npm install -g vercel
            displayName: 'Install Vercel CLI'

          - script: |
              cd Frontend
              vercel --prod --token $(VERCEL_TOKEN) --yes --name fringe-booking-project
            displayName: 'Deploy Frontend to Vercel'

          - task: DownloadSecureFile@1
            name: downloadProfile
            inputs:
              secureFile: 'fringebooking-profile'

          - task: PowerShell@2
            displayName: 'Deploy Backend to Azure App Service (Spring Boot JAR)'
            inputs:
              targetType: 'inline'
              script: |
                $folder = "$(System.DefaultWorkingDirectory)\Backend\target"
                $filePath = Get-ChildItem $folder -Filter '*-SNAPSHOT.jar' | Select-Object -ExpandProperty FullName

                if (-not $filePath) {
                  Write-Error "❌ JAR file not found in $folder"
                  exit 1
                }

                Write-Host "✅ Found JAR: $filePath"

                # Parse only the first publishProfile node
                $publishProfileNode = ([xml]$publishProfile).publishData.publishProfile | Select-Object -First 1

                # Extract values as strings
                $userName = $publishProfileNode.userName.ToString()
                $password = $publishProfileNode.userPWD.ToString()
                $deployUrl = $publishProfileNode.publishUrl.ToString()

                # Convert to credential
                $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
                $credential = New-Object System.Management.Automation.PSCredential($userName, $securePassword)

                # Deploy the JAR
                Invoke-WebRequest -Uri "https://$deployUrl/api/zipdeploy" `
                                  -Method POST `
                                  -InFile $filePath `
                                  -Headers @{"Content-Type"="application/octet-stream"} `
                                  -Credential $credential
