trigger:
  branches:
    include:
      - main
      - dev
      - test

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals LAPTOP-DROUUN5U


variables:
  - group: vercel-deploy-group
  - name: node_version
    value: '18'


stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Frontend and Backend
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            workingDirectory: Frontend
            displayName: 'Build Frontend'


          - script: |
              echo JAVA_HOME=$JAVA_HOME
              java -version
              cd Backend
              ./mvnw.cmd clean package --no-transfer-progress
            displayName: 'Build Backend (Java + Maven)'

  - stage: Test
    dependsOn: Build
    displayName: Test Stage
    jobs:
      - job: TestJob
        displayName: Run Tests
        steps:
          - checkout: self

          - script: |
              npm ci
              npm test
            workingDirectory: Frontend
            displayName: 'Test Frontend'

          - script: |
              cd Backend
              ./mvnw.cmd test -e -X
            displayName: 'Test Backend'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'Backend Unit Tests'
              failTaskOnMissingResultsFile: false
            condition: succeededOrFailed()
            displayName: 'Publish Test Results'

  - stage: Deploy
    dependsOn: Test
    displayName: Deploy Stage
    jobs:
      - job: DeployJob
        displayName: Deploy Frontend and Backend
        steps:
          - checkout: self

          - script: npm install -g vercel
            displayName: 'Install Vercel CLI'

          - script: |
              cd Frontend
              vercel --prod --token $(VERCEL_TOKEN) --yes --name fringe-booking-project
            displayName: 'Relink and Deploy Frontend to Vercel'


          - task: DownloadSecureFile@1
            name: downloadProfile
            inputs:
              secureFile: 'fringebooking-profile'

          - task: AzureWebApp@1
            displayName: 'Deploy Backend to Azure App Service (Spring Boot JAR)'
            inputs:
              azureSubscription: 'Azure-FringeBooking-ARM'  # e.g., Azure-For-Students
              appType: 'webAppLinux'
              appName: 'fringebooking'                          # Your App Service name
              package: '$(System.DefaultWorkingDirectory)/Backend/target/*.jar'
              runtimeStack: 'JAVA|17-java17'

