trigger:
  branches:
    include:
      - dev
      - test
      - main

pool:
  name: 'development'
  demands:
    - Agent.Name -equals LAPTOP-DROUUN5U

variables:
  node_version: '18'
  working_dir: 'frontend'

stages:
  - stage: Build
    displayName: Build Frontend
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '$(node_version)'
            displayName: 'Setup Node.js'

          - script: |
              cd $(working_dir)
              npm install
              npm run build
            displayName: 'Install & Build'

  - stage: Test
    displayName: Test Frontend
    dependsOn: Build
    jobs:
      - job: Test
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '$(node_version)'
            displayName: 'Setup Node.js'

          - script: |
              cd $(working_dir)
              npm install
              npm test
            displayName: 'Run Unit Tests'

  - stage: Deploy
    displayName: Deploy Frontend
    dependsOn: Test
    jobs:
      - job: Deploy
        steps:
          - script: |
              echo "🚀 Deploying frontend for branch: $(Build.SourceBranchName)"
              cd $(working_dir)
              npm install
              npm run build
              # Insert your actual deploy command here
              # For Azure Static Web Apps CLI:
              # npx swa deploy --app-name $(Build.SourceBranchName) --env $(Build.SourceBranchName)
            displayName: 'Deploy to $(Build.SourceBranchName)'
