trigger:
  branches:
    include:
      - main

pool:
  name: java_pool  # Your self-hosted agent

variables:
  artifactName: backend-artifact

steps:
# 1. Checkout code
- task: Checkout@1

# 2. Set up Java (optional if already installed on agent)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

# 3. Build the backend using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'Backend/pom.xml'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    goals: 'clean package'

# 4. Publish the built JAR as a pipeline artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Backend/target'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'

# 5. Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure-FringeBooking-ARM'
    appType: 'webApp'
    appName: 'adalaide-backend'
    package: '$(Pipeline.Workspace)/$(artifactName)/*.jar'
