trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals LAPTOP-DROUUN5U

stages:
  - stage: Build
    displayName: 'Build Backend'
    jobs:
      - job: BuildJob
        displayName: 'Build Spring Boot App'
        steps:
          - checkout: self

          - task: Maven@3
            displayName: 'Build with Maven'
            inputs:
              mavenPomFile: 'Backend/pom.xml'
              mavenOptions: '-Xmx1024m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
              goals: 'clean package'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Backend Artifact'
            inputs:
              PathtoPublish: 'Backend/target'
              ArtifactName: 'backend-artifact'
              publishLocation: 'Pipeline'

  - stage: Test
    displayName: 'Run Unit Tests'
    dependsOn: Build
    jobs:
      - job: TestJob
        displayName: 'Execute JUnit Tests'
        steps:
          - checkout: self

          - task: Maven@3
            displayName: 'Run Tests with Maven'
            inputs:
              mavenPomFile: 'Backend/pom.xml'
              mavenOptions: '-Xmx1024m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
              goals: 'test'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Backend Artifact'
            inputs:
              PathtoPublish: 'Backend/target'
              ArtifactName: 'backend-artifact'
              publishLocation: 'Pipeline'

  - stage: Deploy
    dependsOn: Test
    displayName: 'Deploy Backend to Azure'
    jobs:
      - job: DeployJob
        displayName: 'Deploy Spring Boot JAR'
        steps:
          - checkout: self

          - task: DownloadSecureFile@1
            name: downloadProfile
            inputs:
              secureFile: 'fringebooking-profile'  # Replace with your actual filename

          - task: PowerShell@2
            displayName: '✅ Deploy JAR to Azure App Service'
            timeoutInMinutes: 10
            inputs:
              targetType: 'inline'
              script: |
                [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
                
                $artifactFolder = "$(System.ArtifactsDirectory)\backend-artifact"
                $jarFile = Get-ChildItem -Path $artifactFolder -Filter '*.jar' -Recurse | Select-Object -ExpandProperty FullName -First 1

                if (-not $jarFile) {
                  Write-Error "❌ No JAR file found in $artifactFolder"
                  exit 1
                }

                Write-Host "✅ Found JAR: $jarFile"

                $publishProfileXml = [xml](Get-Content "$(downloadProfile.secureFilePath)")
                $profile = $publishProfileXml.publishData.publishProfile | Where-Object { $_.publishMethod -eq 'ZipDeploy' }

                $userName = $profile.userName
                $password = $profile.userPWD
                $publishUrl = $profile.publishUrl

                if ($publishUrl -notlike 'https://*') {
                  $publishUrl = "https://$publishUrl"
                }

                $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
                $credential = New-Object System.Management.Automation.PSCredential($userName, $securePassword)

                try {
                  Invoke-RestMethod -Uri "$publishUrl/api/zipdeploy" `
                                    -Method POST `
                                    -InFile $jarFile `
                                    -Headers @{"Content-Type" = "application/octet-stream"} `
                                    -Credential $credential `
                                    -TimeoutSec 300
                  Write-Host "✅ Deployment to Azure App Service completed successfully."
                  Write-Host "`n🌐 App is now live at:"
                  Write-Host "👉 https://adalaide-backend-1747617833788.azurewebsites.net/"
                }
                catch {
                  Write-Error "❌ Deployment failed: $($_.Exception.Message)"
                  exit 1
                }
