trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals fringeagent-vm

variables:
  - group: vercel-deploy-group
  - name: node_version
    value: '18'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Frontend Only
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            workingDirectory: Frontend
            displayName: 'Build Frontend'

  - stage: Test
    dependsOn: Build
    displayName: Test Stage
    jobs:
      - job: TestJob
        displayName: Run Tests
        steps:
          - checkout: self

          - script: |
              npm ci
              npm test
            workingDirectory: Frontend
            displayName: 'Test Frontend'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'Backend Unit Tests'
              failTaskOnMissingResultsFile: false
            condition: succeededOrFailed()
            displayName: 'Publish Test Results'

  - stage: Deploy
    dependsOn: Test
    displayName: Deploy Stage
    jobs:
      - job: DeployJob
        displayName: Deploy Frontend and Backend
        steps:
          - checkout: self

          - script: npm install -g vercel
            displayName: 'Install Vercel CLI'

          - script: |
              cd Frontend
              vercel --prod --token $(VERCEL_TOKEN) --yes --name fringe-booking-project
            displayName: 'Deploy Frontend to Vercel'

          - task: DownloadSecureFile@1
            name: downloadProfile
            inputs:
              secureFile: 'fringebooking-profile'

          - task: AzureWebApp@1
            displayName: 'Deploy Backend JAR to Azure App Service'
            inputs:
              azureSubscription: 'Azure-FringeBooking-ARM'     # 👈 Use this exact name from your screenshot
              appType: 'webApp'
              appName: 'fringebooking'                         # 👈 Must exactly match your App Service name
              package: '$(System.DefaultWorkingDirectory)/Backend/target/adalaide-backend-0.0.1-SNAPSHOT.jar'
