trigger:
  branches:
    include:
      - main
      - dev
      - test

pool:
  name: 'development'
  demands:
    - Agent.Name -equals LAPTOP-DROUUN5U

variables:
  node_version: '18'
  java_version: '17'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Frontend and Backend
        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
            displayName: 'Install Node.js'

          - script: |
              cd frontend
              npm install
              npm run build
            displayName: 'Build Frontend'

          - task: JavaToolInstaller@0
            inputs:
              versionSpec: $(java_version)
              jdkArchitectureOption: x64
            displayName: 'Install Java'

          - script: |
              cd Backend
              ./mvnw.cmd clean package --no-transfer-progress
            displayName: 'Build Backend'

  - stage: Test
    dependsOn: Build
    displayName: Test Stage
    jobs:
      - job: TestJob
        displayName: Run Tests
        steps:
          - checkout: self

          - script: |
              cd frontend
              npm ci
              npm test
            displayName: 'Test Frontend'

          - script: |
              cd Backend
              ./mvnw.cmd test
            displayName: 'Test Backend'

  - stage: Deploy
    dependsOn: Test
    displayName: Deploy Stage
    jobs:
      - job: DeployJob
        displayName: Deploy to Vercel & Azure
        steps:
          - checkout: self

          - script: npm install -g vercel
            displayName: 'Install Vercel CLI'

          - script: |
              cd frontend
              vercel --prod --token $(VERCEL_TOKEN)
            displayName: 'Deploy Frontend to Vercel'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'YOUR-SERVICE-CONNECTION-NAME'
              appName: 'fringebooking'
              package: '$(System.DefaultWorkingDirectory)/Backend/target/*.jar'
            displayName: 'Deploy Backend to Azure App Service'
